### ISSUE TITLE
It should be possible to deposit against ORG.ID address

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/trust-clue-lif-deposit#11]
While depositing on behalf of an account is fine, it should actually be possible to deposit to the organization's address and not to some random account. The deposit should (probably) be checking that the depositor is an associated key of organization. Then there's the question of withdrawal - associated keys can be different at the time of deposit and withdrawal. It is unclear how it should behave.

**Comment by czervenka** [comment]
It is important to allow to deposit either on Org.ID address or depositor address but not both to keep the deposit clear and simple. Here is my proposal:

**When checking for Org.ID's deposit amount** there will be no information about what key was used to deposit.

**When depositing:**

- the depositor has to specify an Org.ID address to deposit to
- the depositor's key has to be in Org.ID's associatedKeys

**When requesting withdrawal:**

- depositor can request withdrawal of Lífs of an Org.ID if and only if it is in Org.ID's associatedKeys (at the time of the withdrawal request call).
- any of the Org.ID's associatedKeys can be used to request withdrawal of Org.ID's deposit
- the Lífs being returned will be sent to the associatedKey which initiated the withdrawal request

**Comment by JirkaChadima** [comment]
> When checking for Org.ID's deposit amount there will be no information about what key was used to deposit.

There probably can be, if we want to.

**Comment by czervenka** [comment]
OK, thanks.

**Comment by czervenka** [comment]
@JirkaChadima 
The idea is that Lífs are deposited by Org.ID and not an associatedKey. The keys are just used to authorize the action. Therefor, let's not include list of keys used to top-up deposit in response to Org.ID deposit amount.
