### ISSUE TITLE
Add zos upgradeability

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/trust-clue-lif-deposit#4]
- In the current state, we cannot change the code if some security issue occurs.
- Since the deposits are heavily tied to a token instance (and not a token name, for example), it makes sense that the address cannot be changed after deployment. So I'd stick with the constructor-only decision making on the used token instance.
- Since zos upgradeability does not allow to change the data storage layout, an eventual upgrade should in no way affect the balances.

**Comment by AugustoL** [comment]
fixed in #27
